# Generated by Django 5.0.1 on 2024-01-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumemodel',
            name='exp',
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='projects',
            field=models.TextField(null=True),
        ),
    ]
